In [1]:
import numpy as np
import pyarrow
import pandas as pd

print("numpy:", np.__version__)
print("pyarrow:", pyarrow.__version__)
print("pandas:", pd.__version__)

numpy: 1.26.4
pyarrow: 14.0.2
pandas: 3.0.0

In [7]:
import pandas as pd
df = pd.read_parquet("../data/raw/train_data_0.pq")
df.head()

,id,rn,pre_since_opened,pre_since_confirmed,pre_pterm,pre_fterm,pre_till_pclose,pre_till_fclose,pre_loans_credit_limit,pre_loans_next_pay_summ,...,enc_paym_21,enc_paym_22,enc_paym_23,enc_paym_24,enc_loans_account_holder_type,enc_loans_credit_status,enc_loans_credit_type,enc_loans_account_cur,pclose_flag,fclose_flag
0,0,1,18,9,2,3,16,10,11,3,...,3,3,3,4,1,3,4,1,0,0
1,0,2,18,9,14,14,12,12,0,3,...,0,0,0,4,1,3,4,1,0,0
2,0,3,18,9,4,8,1,11,11,0,...,0,0,0,4,1,2,3,1,1,1
3,0,4,4,1,9,12,16,7,12,2,...,3,3,3,4,1,3,1,1,0,0
4,0,5,5,12,15,2,11,12,10,2,...,3,3,3,4,1,3,4,1,0,0

In [1]:
# импорт и окружение
import sys
from pathlib import Path

# добавляем корень проекта в PYTHONPATH
PROJECT_ROOT = Path("..").resolve()
sys.path.append(str(PROJECT_ROOT))

In [2]:
from src.data_loading import build_base_dataset

In [3]:
df = build_base_dataset()

In [4]:
df.shape

(3000000, 61)

In [5]:
df.head()

,id,rn,pre_since_opened,pre_since_confirmed,pre_pterm,pre_fterm,pre_till_pclose,pre_till_fclose,pre_loans_credit_limit,pre_loans_next_pay_summ,...,enc_paym_21,enc_paym_22,enc_paym_23,enc_paym_24,enc_loans_account_holder_type,enc_loans_credit_status,enc_loans_credit_type,enc_loans_account_cur,pclose_flag,fclose_flag
0,0,5.5,8.100000,7.600000,7.100000,7.500000,11.400000,10.700000,9.600000,3.100000,...,2.400000,2.400000,2.400000,4.000000,1.0,2.600000,3.500000,1.0,0.100000,0.200000
1,1,7.5,11.428571,7.642857,6.642857,7.928571,10.071429,7.000000,8.142857,2.142857,...,2.142857,2.428571,2.357143,3.357143,1.0,2.714286,3.142857,1.0,0.071429,0.142857
2,2,2.0,8.333333,10.666667,7.000000,6.000000,5.000000,9.000000,1.666667,1.333333,...,2.333333,2.333333,2.333333,4.000000,1.0,2.333333,3.333333,1.0,0.666667,0.666667
3,3,8.0,7.000000,7.333333,7.600000,7.800000,5.200000,8.133333,9.866667,2.600000,...,1.600000,1.600000,1.600000,3.000000,1.0,2.533333,3.600000,1.0,0.333333,0.400000
4,4,1.0,12.000000,9.000000,4.000000,8.000000,1.000000,11.000000,12.000000,1.000000,...,3.000000,3.000000,3.000000,4.000000,1.0,2.000000,3.000000,1.0,1.000000,1.000000

In [6]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 61 columns):
 #   Column                         Dtype
---  ------                         -----
 0   id                             int64
 1   rn                             float64
 2   pre_since_opened               float64
 3   pre_since_confirmed            float64
 4   pre_pterm                      float64
 5   pre_fterm                      float64
 6   pre_till_pclose                float64
 7   pre_till_fclose                float64
 8   pre_loans_credit_limit         float64
 9   pre_loans_next_pay_summ        float64
 10  pre_loans_outstanding          float64
 11  pre_loans_total_overdue        float64
 12  pre_loans_max_overdue_sum      float64
 13  pre_loans_credit_cost_rate     float64
 14  pre_loans5                     float64
 15  pre_loans530                   float64
 16  pre_loans3060                  float64
 17  pre_loans6090                  float64
 18  pre_loans90                    float64
 19  is_zero_loans5                 float64
 20  is_zero_loans530               float64
 21  is_zero_loans3060              float64
 22  is_zero_loans6090              float64
 23  is_zero_loans90                float64
 24  pre_util                       float64
 25  pre_over2limit                 float64
 26  pre_maxover2limit              float64
 27  is_zero_util                   float64
 28  is_zero_over2limit             float64
 29  is_zero_maxover2limit          float64
 30  enc_paym_0                     float64
 31  enc_paym_1                     float64
 32  enc_paym_2                     float64
 33  enc_paym_3                     float64
 34  enc_paym_4                     float64
 35  enc_paym_5                     float64
 36  enc_paym_6                     float64
 37  enc_paym_7                     float64
 38  enc_paym_8                     float64
 39  enc_paym_9                     float64
 40  enc_paym_10                    float64
 41  enc_paym_11                    float64
 42  enc_paym_12                    float64
 43  enc_paym_13                    float64
 44  enc_paym_14                    float64
 45  enc_paym_15                    float64
 46  enc_paym_16                    float64
 47  enc_paym_17                    float64
 48  enc_paym_18                    float64
 49  enc_paym_19                    float64
 50  enc_paym_20                    float64
 51  enc_paym_21                    float64
 52  enc_paym_22                    float64
 53  enc_paym_23                    float64
 54  enc_paym_24                    float64
 55  enc_loans_account_holder_type  float64
 56  enc_loans_credit_status        float64
 57  enc_loans_credit_type          float64
 58  enc_loans_account_cur          float64
 59  pclose_flag                    float64
 60  fclose_flag                    float64
dtypes: float64(60), int64(1)
memory usage: 1.4 GB

In [7]:
df.isna().sum().sort_values(ascending=False).head(20)

id             0
enc_paym_1     0
enc_paym_3     0
enc_paym_4     0
enc_paym_5     0
enc_paym_6     0
enc_paym_7     0
enc_paym_8     0
enc_paym_9     0
enc_paym_10    0
enc_paym_11    0
enc_paym_12    0
enc_paym_13    0
enc_paym_14    0
enc_paym_15    0
enc_paym_16    0
enc_paym_17    0
enc_paym_18    0
enc_paym_19    0
enc_paym_20    0
dtype: int64

In [8]:
output_path = PROJECT_ROOT / "data" / "processed" / "dataset.pkl"
output_path.parent.mkdir(parents=True, exist_ok=True)

df.to_pickle(output_path)

output_path

WindowsPath('C:/Users/vdorofeev/PycharmProjects/JupyterProject/ML Junior final/data/processed/dataset.pkl')

In [9]:
df["id"].nunique()

3000000

In [10]:
df.duplicated(subset="id").sum()

0

In [11]:
assert df["id"].is_unique, "ID не уникален — ошибка агрегации"