In [6]:
import pandas as pd
from pathlib import Path
from src.feature_engineering import (
    add_overdue_features,
    add_limit_ratio_features,
    add_credit_timeline_features,
)


PROJECT_ROOT = Path("..").resolve()
DATA_PATH = PROJECT_ROOT / "data" / "processed" / "dataset_with_target.pkl"

df = pd.read_pickle(DATA_PATH)

df.shape

(3000000, 62)

In [7]:
df_fe = add_overdue_features(df)
df_fe = add_limit_ratio_features(df_fe)


df_fe.shape

(3000000, 73)

In [3]:
df_fe[
    [
        "overdue_cnt_total",
        "overdue_cnt_long",
        "share_long_overdue",
        "has_any_overdue",
        "has_90plus_overdue",
        "outstanding_to_limit",
        "overdue_to_limit",
        "over_limit_flag",
    ]
].head()

,overdue_cnt_total,overdue_cnt_long,share_long_overdue,has_any_overdue,has_90plus_overdue,outstanding_to_limit,overdue_to_limit,over_limit_flag
0,39.000000,12.0,0.300000,1,1,0.273585,0.0,0
1,39.000000,12.0,0.300000,1,1,0.320312,0.0,0
2,34.333333,12.0,0.339623,1,1,1.125000,0.0,0
3,39.000000,12.0,0.300000,1,1,0.300613,0.0,0
4,39.000000,12.0,0.300000,1,1,0.230769,0.0,0

In [4]:
df_fe[
    [
        "credit_age_ratio",
        "time_to_close_ratio",
        "is_new_credit",
        "is_near_close",
        "is_long_credit",
        "is_closed_fact",
    ]
].describe()

,credit_age_ratio,time_to_close_ratio,is_new_credit,is_near_close,is_long_credit,is_closed_fact
count,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06
mean,1.154172e+00,8.428703e-01,1.191933e-02,1.235067e-02,4.968700e-01,5.614900e-02
std,9.324560e-01,8.502731e-01,1.085231e-01,1.104452e-01,4.999903e-01,2.302093e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,7.826087e-01,5.781250e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000e+00,7.342657e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.279720e+00,9.186047e-01,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
max,1.900000e+01,1.600000e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [8]:
OUT_PATH = PROJECT_ROOT / "data" / "processed" / "dataset_fe_AB.pkl"
df_fe.to_pickle(OUT_PATH)

OUT_PATH

WindowsPath('C:/Users/vdorofeev/PycharmProjects/JupyterProject/ML Junior final/data/processed/dataset_fe_AB.pkl')